const images = [
    {
        id: 1,
        src: "/photography/1.jpg",
        alt: "Photo 1",
        height: 2000,
        width: 1333,
    },  
    {
        id: 2,
        src: "/photography/2.jpg",
        alt: "Photo 2",
        height: 2000,
        width: 1333,
    },
    {
        id: 3,
        src: "/photography/3.jpg",
        alt: "Photo 3",
        height: 864,
        width: 1080,
    },
    {
        id: 4,
        src: "/photography/4.jpg",
        alt: "Photo 4",
        height: 864,
        width: 1080,
    },
    {
        id: 5,
        src: "/photography/5.jpg",
        alt: "Photo 5",
        height: 1398,
        width: 1748,
    },
    {
        id: 6,
        src: "/photography/6.jpg",
        alt: "Photo 6",
        height: 2000,
        width: 1600,
    },
    {
        id: 7,
        src: "/photography/7.jpg",
        alt: "Photo 7",
        height: 2000,
        width: 1600,
    },
    {
        id: 8,
        src: "/photography/8.jpg",
        alt: "Photo 8",
        height: 2000,
        width: 1600,
    },
    {
        id: 9,
        src: "/photography/9.jpg",
        alt: "Photo 9",
        height: 2000,
        width: 1600,
    },
    {
        id: 10,
        src: "/photography/10.jpg",
        alt: "Photo 10",
        height: 2000,
        width: 1333,
    },
    {
        id: 11,
        src: "/photography/11.jpg",
        alt: "Photo 11",
        height: 2000,
        width: 1333,
    },
    {
        id: 12,
        src: "/photography/12.jpg",
        alt: "Photo 12",
        height: 2000,
        width: 1333,
    },
    {
        id: 13,
        src: "/photography/13.jpg",
        alt: "Photo 13",
        height: 1333,
        width: 2000,
    },
    {
        id: 14,
        src: "/photography/14.jpg",
        alt: "Photo 14",
        height: 1333,
        width: 2000,
    },
    {
        id: 15,
        src: "/photography/15.jpg",
        alt: "Photo 15",
        height: 2000,
        width: 1333,
    },
    {
        id: 16,
        src: "/photography/16.jpg",
        alt: "Photo 16",
        height: 2000,
        width: 1599,
    },
    {
        id: 17,
        src: "/photography/17.jpg",
        alt: "Photo 17",
        height: 2000,
        width: 1333,
    },
    {
        id: 18,
        src: "/photography/18.jpg",
        alt: "Photo 18",
        height: 1600,
        width: 2000
    },
    {
        id: 19,
        src: "/photography/19.jpg",
        alt: "Photo 19",
        height: 2000,
        width: 1600,
    },
    {
        id: 20,
        src: "/photography/20.jpg",
        alt: "Photo 20",
        height: 2000,
        width: 1333,
    },
    {
        id: 21,
        src: "/photography/21.jpg",
        alt: "Photo 21",
        height: 2000,
        width: 1333,
    },
    {
        id: 22,
        src: "/photography/22.jpg",
        alt: "Photo 22",
        height: 1333,
        width: 2000,
    },
    {
        id: 23,
        src: "/photography/23.jpg",
        alt: "Photo 23",
        height: 2000,
        width: 1333,
    },
    {
        id: 24,
        src: "/photography/24.jpg",
        alt: "Photo 24",
        height: 2000,
        width: 1331,
    },
    {
        id: 25,
        src: "/photography/25.jpg",
        alt: "Photo 25",
        height: 1333,
        width: 2000,
    },
    {
        id: 26,
        src: "/photography/26.jpg",
        alt: "Photo 26",
        height: 1333,
        width: 2000,
    },
    {
        id: 27,
        src: "/photography/27.jpg",
        alt: "Photo 27",
        height: 1333,
        width: 2000,
    },
    {
        id: 28,
        src: "/photography/28.jpg",
        alt: "Photo 28",
        height: 2000,
        width: 1333,
    },
    {
        id: 29,
        src: "/photography/29.jpg",
        alt: "Photo 29",
        height: 2000,
        width: 1333,
    },
    {
        id: 30,
        src: "/photography/30.jpg",
        alt: "Photo 30",
        height: 2000,
        width: 1333,
    },

    
];

export default images;
