import Head from "next/head";
import React from "react";
import { styled } from "../stitches.confing";
import { motion, useTransform } from "framer-motion";
import { useScroll, useInView } from "framer-motion";

import Header from "../components/Header/Header";
import SelectedWorks from "../components/SelectedWorks/SelectedWorks";
import Footer from "../components/Footer/Footer";
import Modal from "../components/Modal/Modal";
import Text from "../components/Text/Text";
// import {
//   AccordionContainer,
//   AccordionItem,
//   AccordionTrigger,
//   AccordionContent,
// } from "../components/Accordion/AccordionTest";

export default function Home() {
  const [isOpen, setIsOpen] = React.useState(false);
  const workRef = React.useRef(null);
  const isInView = useInView(workRef, {
    margin: "0px 0px 0px 0px",
  });
  const { scrollYProgress } = useScroll({
    target: workRef,
    offset: ["start end", "start start"],
  });

  // const scale = useTransform(scrollYProgress, [0, 1], [0.96, 1]);
  // const opacity = useTransform(scrollYProgress, [0, 1.2], [0.0, 1]);
  // const y = useTransform(scrollYProgress, [0, 1], ["20%", "0%"]);
  // const blur = useTransform(
  //   scrollYProgress,
  //   (value) => `blur(${(1 - value) * 5}px)`
  // );

  return (
    <>
      <Head>
        <title>Rafał Ziółek ✴ Product Designer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setIsOpen={setIsOpen} />
      <motion.div
        ref={workRef}
        style={{
          opacity: isInView ? 1 : 0,
          // scale: isInView ? 1 : 0.8,
          transform: isInView ? "translateY(0%)" : "translateY(5%)",
          filter: isInView ? "blur(0px)" : "blur(30px)",
          transition: "all 1s cubic-bezier(0.17, 0.55, 0.55, 1)",
        }}
      >
        <SelectedWorks />
      </motion.div>
      <Modal isOpen={isOpen} setIsOpen={setIsOpen}>
        <Text>Siema siema</Text>
      </Modal>

      <Footer></Footer>
    </>
  );
}
