import Head from "next/head";
import Image from "next/image";
import { styled } from "../stitches.confing";
import Box from "../components/Box";
import { Text } from "../components/Text";
import Link from "next/link";
import Project from "../components/Project";
import { Divider } from "../components/Divider";
import { ExternalLink } from "../components/ExternalLink";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rafał Ziółek ✴ Product Designer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        {/* ---Header--- */}
        <Box
          as="header"
          css={{
            justifyContent: "end",
            minHeight: "40vh",
            margin: "$s",
            display: "flex",
            flexDirection: "column",
            gap: "$",

            "@bp1": {
              marginX: "$m",
            },

            "@bp3": {
              height: "35vh",
            },
          }}
        >
          <Text type="mainHeading" as="h1" css={{ maxWidth: "40ch" }}>
            I am Rafał Ziółek — Digital Product Designer.
            <Text as="span" type="mainHeading" secondary>
              <br />
              Currently working on design systems at Docplanner.
            </Text>
          </Text>

          <Box
            css={{
              margin: "$l 0 0 0",
              display: "flex",
              gap: "$m",
            }}
          >
            <ExternalLink href="https://read.cv/rafalziolek">
              read.cv
            </ExternalLink>
            <ExternalLink href="https://twitter.com/rafal_ziolek">
              Twitter
            </ExternalLink>
            <ExternalLink href="https://github.com/rafalziolek">
              Github
            </ExternalLink>
          </Box>
        </Box>

        {/* ---Projects--- */}
        <Box
          css={{
            margin: "0 $m $xl $m",
            paddingTop: "$s",
            rowGap: "$s",
          }}
        >
          <Box
            grid
            css={{
              display: "grid",
              gridTemplateColumns: "100%",
              rowGap: "$l",
              columnGap: "$s",
              "@bp2": {
                gridTemplateColumns: "repeat( 2,1fr )",
              },
            }}
          >
            <Project
              style={{
                backgroundColor: "#B8EFE8",
                gridColumn: "span 2",
              }}
              projectName="Watson"
              title="Watson Design System"
              caption="Docplanner's design language for our SaaS product and digital experience."
            />
            <Project
              projectName="Nikola"
              title="Nikola Chmiel"
              caption=" Personal website for a certified yoga teacher"
            />
            <Project
              video
              projectName="Watson"
              title="Watson Design System"
              caption="Docplanner's design language for our SaaS product and digital experience."
            />
            <Project
              video
              projectName="Nikola"
              title="Nikola Chmiel"
              caption=" Personal website for a certified yoga teacher"
            />
          </Box>
        </Box>
      </Box>
    </>
  );
}
