import Header from "../Components/Header";
import Text from "../Components/Text";
import Stack from "../Components/Stack";
import Table from "../Components/Table";
import Icon from "../Components/Icon";
import Container from "../Components/Container";
import Link from "next/link";
import { StyledLink } from "../Components/Link";

const experience = {
    // columns: ['Experience', 'Position', 'Period'],
    rows: [
        {
            position: 'Product Designer',
            company: 'Docplanner',
            period: '2018  →  Now'
        },
        {
            position: 'Freelance Product Designer',
            company: 'Semiflat',
            period: '2021  →  2022'
        },
        {
            position: 'UI/UX Designer',
            company: 'Absolvent Group',
            period: '2018  →  2018'
        },
        {
            position: 'UI Designer',
            company: 'INVO',
            period: '2018  →  2018'
        },
    ]
}

function Me() {
    return ( 
        <>
            <Header>
                <Stack flexDirection='column' gap='l'>
                    <Text tag="h1" type='MainHeading'>Product Designer based in Poland with 5 years of experience.</Text>
                    <Text>For the past year, I have been building a design system at Docplanner with a goal to create a design system that is easy to use and implement, so that product teams can build products quickly, with consistent UX and UI. Before transitioning to design systems I was designing SaaS software for doctors</Text>
                    <Text>Apart from being a designer, I am a photography enthusiast. You can check my photos here. I also cook. A lot.</Text>
                    <Text>This text was generated by Open AI (lol)</Text>
                </Stack>
            </Header>
            <Container bottom='xl'>
                <Stack flexDirection='column' gap='s'>
                    <Stack flexDirection='row' gap='xxs' alignItems='center'>
                        <Text tag="h3" type='SubSectionHeading'>Experience</Text>
                        <Icon name='arrowAngledDown' size='40' color='black'/>
                    </Stack>
                    <Table tableData={experience}></Table>
                </Stack>
            </Container>
            <Container bottom='xl'>
                <Stack flexDirection='column' gap='s'>
                    <Stack flexDirection='row' gap='xxs' alignItems='center'>
                            <Text tag="h3" type='SubSectionHeading'>Find me</Text>
                            <Icon name='arrowAngledDown' size='40' color='black'/>
                    </Stack>
                    <Stack flexDirection='row' gap='s'>
                        <Link href='https://twitter.com/rafal_ziolek' passHref legacyBehavior><StyledLink>Twitter</StyledLink></Link>
                        <Link href='https://www.linkedin.com/in/rafal-ziolek/' passHref legacyBehavior><StyledLink>LinkedIn</StyledLink></Link>
                        <Link href='https://github.com/rafalziolek' passHref legacyBehavior><StyledLink>GitHub</StyledLink></Link>

                    </Stack>
                </Stack>
            </Container>
        </>
    )

}

export default Me;