import { styled } from "../stitches.confing";
import Box from "../components/Box";
import { Text } from "../components/Text";
import { ExperienceTable, TableItem } from "../components/ExperienceTable";
import Image from "next/image";

const experience = {
  rows: [
    {
      position: "Product Designer",
      company: "Docplanner",
      period: "2018  →  Now",
    },
    {
      position: "Freelance Product Designer",
      company: "Semiflat",
      period: "2021  →  2022",
    },
    {
      position: "UI/UX Designer",
      company: "Absolvent Group",
      period: "2018  →  2018",
    },
    {
      position: "UI Designer",
      company: "INVO",
      period: "2018  →  2018",
    },
  ],
};

function me() {
  return (
    <Box
      container
      css={{
        // backgroundImage: 'url(../assets/noise.svg)',
        backgroundRepeat: "repeat",
      }}
    >
      {/* Header */}
      <Box
        grid
        as="header"
        css={{
          rowGap: "$m",
          margin: "$xl $m $xl $m",
        }}
      >
        <Text
          type="heading"
          as="h1"
          css={{ marginBottom: "$l", maxWidth: "45ch", gridColumn: "span 8" }}
        >
          I am a product designer based in Warsaw, Poland. Currently at
          Docplanner. My expertise is design system and interaction design
        </Text>
        <Text
          as="p"
          type="body"
          css={{
            marginBottom: "$s",
            gridColumn: "1/6",
          }}
        >
          My specialty is creating design systems that are scalable, consistent,
          and intuitive. Throughout my career, I have worked on a variety of
          projects for different platforms, and most recently have had the
          opportunity to improve the SaaS product for doctors at Docplanner.
          <br />
          <br />
          Currently, I am working on design systems in Docplanner, leveraging my
          expertise in this area to create an exceptional user experience. With
          my strong background in product design and my ability to create
          cohesive design systems, I am well-equipped to take on any challenge
          that comes my way. <br />
          <br />
          <Text as="span" type="body" muted>
            This text was generated by Open AI (lol)
          </Text>
        </Text>
        <figure
          style={{ gridColumn: "7 / 13", width: "100%", height: "800px" }}
        >
          <Image
            src="/assets/me_photo_2.jpg"
            height={4032}
            width={3024}
            style={{
              gridColumn: "7 / 13",
              width: "100%",
              height: "800px",
              objectPosition: "bottom",
              objectFit: "cover",
              borderRadius: "var(--radius-s)",
            }}
            alt="Photo of me taking a selfie in a mirror with a camera in a sunny room"
          />
          <figcaption style={{ color: "var(--colors-gray400)" }}>
            Yes, this is a mirror selfie
          </figcaption>
        </figure>
      </Box>

      {/* Experience */}
      <Box
        grid
        css={{
          padding: "$m 0 $xl 0",
          margin: "0 $m",
          borderTop: "2px solid black",
        }}
      >
        <Text
          as="h3"
          type="heading"
          css={{ marginBottom: "$m", gridColumn: "span 4" }}
        >
          Experience
        </Text>
        <ExperienceTable css={{ gridColumn: "span 8" }}>
          <TableItem
            company="Docplanner"
            title="Product Designer"
            start="2018"
          ></TableItem>
          <TableItem
            company="Semiflat"
            title="Freelance Product Designer"
            start="2021"
            end="2022"
          ></TableItem>
          <TableItem
            company="Absolvent Group"
            title="Junior UI/UX Designer"
            start="2018"
            end="2018"
          ></TableItem>
          <TableItem
            company="INVO"
            title="UI/UX Designer"
            start="2018"
            end="2018"
          ></TableItem>
        </ExperienceTable>
      </Box>
      <Box
        grid
        css={{
          padding: "$m 0 $xl 0",
          margin: "0 $m",
          borderTop: "2px solid black",
        }}
      >
        <Text
          as="h3"
          type="heading"
          css={{ marginBottom: "$m", gridColumn: "span 4" }}
        >
          Outside of work
        </Text>
        <Text
          as="p"
          type="body"
          css={{
            marginBottom: "$s",
            gridColumnStart: "5",
            gridColumnEnd: "13",
          }}
        >
          I am really into photography. When I travel I tend to just walk
          through the cities and take photos of everything. You can check my
          photos on my instagram. Apart from photography I looooove to cook.
        </Text>
      </Box>
    </Box>
  );
}

export default me;
